table1.png:
	qrencode -s 10 -o "table1.png" "http://wifood.sillybytes.net/mesa/1"
	qrencode -s 10 -o "table2.png" "http://wifood.sillybytes.net/mesa/2"
	qrencode -s 10 -o "table3.png" "http://wifood.sillybytes.net/mesa/3"
	qrencode -s 10 -o "table4.png" "http://wifood.sillybytes.net/mesa/4"
	qrencode -s 10 -o "table5.png" "http://wifood.sillybytes.net/mesa/5"
	qrencode -s 10 -o "table6.png" "http://wifood.sillybytes.net/mesa/6"
	qrencode -s 10 -o "table7.png" "http://wifood.sillybytes.net/mesa/7"
	qrencode -s 10 -o "table8.png" "http://wifood.sillybytes.net/mesa/8"
	qrencode -s 10 -o "table9.png" "http://wifood.sillybytes.net/mesa/9"
	qrencode -s 10 -o "table10.png" "http://wifood.sillybytes.net/mesa/10"

clean:
	rm *.png
